/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amspractice.View;

import amspractice.Controller.SQLConnection;
import amspractice.Model.Patron;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author ramon
 */
public class TestPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form TestPanel2
     */
    private SQLConnection sqlCon;
    private String fName, lName, sex, hPhone;
    private int accountType;
    public TestPanel2() {
        initComponents();
      
        sqlCon = new SQLConnection();
        this.setPreferredSize(new Dimension(300, 500));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accouuntTypeLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        fNameLabel = new javax.swing.JLabel();
        fNameTextField = new javax.swing.JTextField();
        lNameLabel = new javax.swing.JLabel();
        laNameTextField = new javax.swing.JTextField();
        sexLabel = new javax.swing.JLabel();
        hPhoneLabel = new javax.swing.JLabel();
        hPhoneTextField = new javax.swing.JTextField();
        sexComboBox = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        accouuntTypeLabel.setText("Account Type");
        accouuntTypeLabel.setToolTipText("");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - Corporate Revenue", "2 - Individual Non-Revenue", "3 - Individual Revenue", "4 - Corporate Individual Revenue", "5 - Corporate Non-Rev" }));

        fNameLabel.setText("First Name");

        lNameLabel.setText("Last Name");

        sexLabel.setText("Sex");

        hPhoneLabel.setText("Home Phone");

        hPhoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hPhoneTextFieldActionPerformed(evt);
            }
        });

        sexComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        sexComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexComboBoxActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fNameLabel)
                            .addComponent(lNameLabel)
                            .addComponent(sexLabel)
                            .addComponent(hPhoneLabel))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hPhoneTextField)
                            .addComponent(laNameTextField)
                            .addComponent(fNameTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accouuntTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accouuntTypeLabel)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNameLabel)
                    .addComponent(laNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexLabel)
                    .addComponent(sexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hPhoneLabel)
                    .addComponent(hPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hPhoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hPhoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hPhoneTextFieldActionPerformed

    private void sexComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexComboBoxActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        Patron np = new Patron();
        np.setAccountType(typeComboBox.getSelectedIndex() + 1);
        np.setfName(fNameTextField.getText());
        np.setlName(laNameTextField.getText());
        np.sethPhone(hPhoneTextField.getText());
        np.setSex(sexComboBox.getSelectedItem().toString());

        System.out.println(np.getfName() + " " + np.getlName());

        String sql = "INSERT INTO Patrons (account_type, first_name, last_name, sex, home_phone) VALUES (?, ?, ?, ?, ?)";

        try(Connection conn = sqlCon.getConnection(); PreparedStatement stmt = conn.prepareStatement(sql);){

            stmt.setInt(1, np.getAccountType());
            stmt.setString(2, np.getfName());
            stmt.setString(3, np.getlName());
            stmt.setString(4, np.getSex());
            stmt.setString(5, np.gethPhone());

            //String SQL = "SELECT * FROM Patrons";
            /*ResultSet rs = stmt.executeQuery(SQL);
            while(rs.next()){
                System.out.println(rs.getString("first_name"));
            }*/
            int x = stmt.executeUpdate();
            //int x = 1;
            if(x > 0){
                System.out.print("Records successfully saved.");
                JOptionPane.showMessageDialog(null, "Patron registered successfully.");
            }
            else{
                System.out.print("Patron not registered");
                JOptionPane.showMessageDialog(null, "Patron not registered.");

            }

            System.out.println("x");

        }
        catch(SQLException e){
            e.printStackTrace();
        }

        fNameTextField.setText("");
        laNameTextField.setText("");
        hPhoneTextField.setText("");
        typeComboBox.setSelectedIndex(0);

    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accouuntTypeLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JTextField fNameTextField;
    private javax.swing.JLabel hPhoneLabel;
    private javax.swing.JTextField hPhoneTextField;
    private javax.swing.JLabel lNameLabel;
    private javax.swing.JTextField laNameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox<String> sexComboBox;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JComboBox<String> typeComboBox;
    // End of variables declaration//GEN-END:variables
}
